# Generated by Django 2.1.7 on 2019-04-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
